#!/bin/bash

echo -e "\033[0;34m-- Format dart files --\033[0m"

# Determine which files are modified by the commit.
CHANGED_FILES=$(git diff --cached --name-status | awk '/^[^D].+\.dart$/{ print $NF }')

# If there is no files to format, skip
[ -z "$CHANGED_FILES" ] && exit 0

# Format the files
dart format $CHANGED_FILES
